name: flexidate
version: 0.8.0+3
homepage: https://github.com/ericmartineau/flexidate
description: A flexible date parsing and handling library
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
  dartx: ^0.7.1
  dartxx: ^0.5.3+2
  equatable: ^2.0.3
  inflection3: ^0.5.3+2
  intl: ^0.17.0
  logging: ^1.0.2
  timezone: ^0.8.0
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
